<?php

namespace ModelBundle\Repository;

/**
 * FollowersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FollowersRepository extends \Doctrine\ORM\EntityRepository
{
}
